### ISSUE TITLE
Universal styles

### ISSUE THREAD

**Issue by jim-rosales** [MissRach89/dasmoto#4]
Great job making use of universal styles!

https://github.com/MissRach89/prj-rev-bwfs-dasmoto/blob/018caa48ced287f294a1a6f30e9b45f47150aa76/Dasmoto/resources/css/style.css#L1-L3

**Comment by MissRach89** [comment]
Thank you Jim! I saw it used once in one of the demo files, even though it wasn't in the actual instructions. Glad it's ok to use :)
