### ISSUE TITLE
Character entity use

### ISSUE THREAD

**Issue by jim-rosales** [MissRach89/dasmoto#5]
If you take a look at this line of code below, currently the `&` symbol is highlighted in red. The reason for this is because in HTML the `&` symbol is a reserved character that is used to add special characters via an [entity reference](https://developer.mozilla.org/en-US/docs/Glossary/Entity). 

To fix this all you need to do is add the ampersand symbol via its entity reference by replacing `&` with `&amp;`

https://github.com/MissRach89/prj-rev-bwfs-dasmoto/blob/018caa48ced287f294a1a6f30e9b45f47150aa76/Dasmoto/index.html#L11

**Comment by MissRach89** [comment]
This is really helpful! I will update it on my local sample now and make a note so I remember :)
