### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jim-rosales** [MissRach89/dasmoto#6]
Grade: Exceeds Expectations

Summary:
Rachael, congrats on finishing the Dasmoto project! Overall you did an excellent job implementing all the required specifications. You did an excellent job making use of all the elements you learned about thus far and applying all your CSS styles efficiently. 

The only improvement I believe you can make on this project and future projects is by adding comments to both your HTML and CSS files. Adding comments is essential as it increases the readability of your code which helps promote collaboration in teams.

**Comment by MissRach89** [comment]
Thank you @jim-rosales for your feedback. I'll go back and add better comments to my first project now, and remember to do so in all future ones 👍
